Failed to parse XML documents when the datatypes in the same elements are structural data type and non-structural data type
https://github.com/databricks/spark-xml/issues/103

Currently, it fails to load XML documents having different data types (structural data types and non-structural data types) for the same elements.

For example,

```xml
<?xml version="1.0"?>
<ROWSET>
    <ROW>
        <user><id>1</id></user>
    </ROW>
    <ROW>
        <user>1234</user>
    </ROW>
</ROWSET>
```

In the case above, this infers the type for `user` as `StringType` as below:
```bash
root
 |-- user: string (nullable = true)
```

- **Before**

this fails to parse throwing the exception below:

```java
15:39:54.518 ERROR org.apache.spark.executor.Executor: Exception in task 0.0 in stage 1.0 (TID 1)
scala.MatchError: StringType (of class org.apache.spark.sql.types.StringType$)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$convertComplicatedType$1$1.apply(StaxXmlParser.scala:86)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$convertComplicatedType$1$1.apply(StaxXmlParser.scala:86)
	at com.databricks.spark.xml.parsers.StaxXmlParser$.convertField(StaxXmlParser.scala:94)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$com$databricks$spark$xml$parsers$StaxXmlParser$$convertObject$1.apply$mcVI$sp(StaxXmlParser.scala:254)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$com$databricks$spark$xml$parsers$StaxXmlParser$$convertObject$1.apply(StaxXmlParser.scala:232)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$com$databricks$spark$xml$parsers$StaxXmlParser$$convertObject$1.apply(StaxXmlParser.scala:232)
	at scala.Option.foreach(Option.scala:257)
...
```

- **After**

```xml
+----------+
|      user|
+----------+
|<id>1</id>|
|      1234|
+----------+
```

Since JSON data source parses this as string just like the above, this PR resembles the behaviour.

This PR also includes some code style corrections for parameters in classes and arguments.

Author: hyukjinkwon <gurwls223@gmail.com>

Closes #106 from HyukjinKwon/ISSUE-105.